package lab.io.rush.exception;

public class UserNotFoundException extends Exception{

}
